name: Trigger E2E GitLab

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger-e2e-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Disparar pipeline E2E no GitLab
        run: |
          curl --fail --request POST \
          --form token="${{ secrets.E2E_TRIGGER_TOKEN }}" \
          --form ref="master" \
          "https://gitlab.com/api/v4/projects/${{ secrets.E2E_PROJECT_ID }}/trigger/pipeline"
