name: Trigger E2E Tests

on:
  push:
    branches:
      - master
      - develop

jobs:

  trigger-e2e:

    runs-on: ubuntu-latest

    steps:

      - name: Disparar pipeline E2E
        run: |

          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.E2E_REPO_TOKEN }}" \
          https://api.github.com/repos/allanbraquiel/testes-cypress-e2e/dispatches \
          -d '{"event_type":"run-e2e-tests"}'